# Generated by Django 3.1.4 on 2022-09-06 11:30

import _socket
from django.db import migrations, models
import django.utils.timezone
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_reports', '0010_dashboardstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationEnrollments',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=150, unique=True, verbose_name='Variable')),
                ('janssen', models.PositiveIntegerField(default=0, verbose_name='Janssen Enrollments')),
                ('sinovac', models.PositiveIntegerField(default=0, verbose_name='Sinovac Enrollments')),
                ('pfizer', models.PositiveIntegerField(default=0, verbose_name='Pfizer Enrollments')),
                ('moderna', models.PositiveIntegerField(default=0, verbose_name='Moderna Enrollments')),
                ('astrazeneca', models.PositiveIntegerField(default=0, verbose_name='Astrazeneca Enrollments')),
                ('months', models.TextField()),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='dashboardstatistics',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.RemoveField(
            model_name='screeningstatistics',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='screeningstatistics',
            name='passed',
        ),
        migrations.AddField(
            model_name='dashboardstatistics',
            name='created',
            field=models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow),
        ),
        migrations.AddField(
            model_name='dashboardstatistics',
            name='device_created',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='dashboardstatistics',
            name='device_modified',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='dashboardstatistics',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AddField(
            model_name='dashboardstatistics',
            name='hostname_modified',
            field=edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50),
        ),
        migrations.AddField(
            model_name='dashboardstatistics',
            name='modified',
            field=models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow),
        ),
        migrations.AddField(
            model_name='dashboardstatistics',
            name='revision',
            field=django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision'),
        ),
        migrations.AddField(
            model_name='dashboardstatistics',
            name='user_created',
            field=edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created'),
        ),
        migrations.AddField(
            model_name='dashboardstatistics',
            name='user_modified',
            field=edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified'),
        ),
        migrations.AddField(
            model_name='enrollmentstatistics',
            name='months',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screeningstatistics',
            name='dose1',
            field=models.PositiveIntegerField(default='', verbose_name='First dose screening'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screeningstatistics',
            name='dose2',
            field=models.PositiveIntegerField(default='', verbose_name='Second dose screening'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screeningstatistics',
            name='dose3',
            field=models.PositiveIntegerField(default='', verbose_name='Booster dose screening'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationstatistics',
            name='months',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboardstatistics',
            name='id',
            field=edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
    ]
